current_version: 1.1.1
replaces:
- file: wp-content/plugins/atareao-functionality/atareao-functionality.php
  pattern: define('ATAREAO_PLUGIN_VERSION',\s*'{{current_version}}');
- file: wp-content/themes/atareao-theme/style.css
  pattern: Version:\s*{{current_version}}
