current_version: 1.0.7
commit: true
tag: true
files:
  - wp-content/plugins/atareao-functionality/atareao-functionality.php:
      - Version
      - ATAREAO_PLUGIN_VERSION
  - wp-content/themes/atareao-theme/style.css:
      - Version
